openapi: 3.0.1
info:
  title: Address Validation 5103 Waiver Power of Attorney API
  description: "The Address Validation API accepts and validates an address and standardizes it for mailing. It can also help you process an address by:\n* Inferring missing or incorrect address components\n* Supplementing an address with additional information, such as geocode, latitude and longitude, and postal service metadata (when available)\n## Technical Overview\nThe Address Validation API returns validated addresses as they appear in the USPS database for domestic addresses. It validates[...]"
  license:
    name: Creative Commons
    url: https://developer.va.gov/terms-of-service
  version: '3'
servers:
- url: https://sandbox-api.va.gov/services/address-validation/{version}
  description: Sandbox
  variables:
    version:
      default: v3
- url: https://api.va.gov/services/address-validation/{version}
  description: Production
  variables:
    version:
      default: v3
security:
- apikey: []
tags:
- name: Power of Attorney
  description: Used for 21-22 and 21-22a form submissions.
paths:
  /forms/2122:
    get:
      summary: Gets schema for POA form.
      deprecated: true
      tags:
      - Power of Attorney
      operationId: GET:/forms/2122
      description: Returns schema to automatically generate a POA form.
    post:
      summary: Submit a POA form.
      tags:
      - Power of Attorney
      operationId: POST:/forms/2122
      security:
      - productionOauth:
        - claim.read
        - claim.write
      - sandboxOauth:
        - claim.read
        - claim.write
      - bearer_token: []
      description: "Signature images\n\n\n\nIf the request includes signature images for both the Veteran and the representative, the API will:\n\n   - Generate VA Form 21-22 PDF for organizations or VA Form 21-22a PDF for individual representatives.\n\n   - Automatically establish POA for the representative.\n\n\n\nThe signature can be provided in either of these formats:\n\n   - Base64-encoded image or signature block. This allows the API to auto-populate and attach the VA Form\n   21-22 witho[...]"
  /forms/2122/{id}:
    put:
      summary: Upload a signed 21-22 document.
      tags:
      - Power of Attorney
      operationId: PUT:/forms/2122/{id}
      security:
      - productionOauth:
        - claim.read
        - claim.write
      - sandboxOauth:
        - claim.read
        - claim.write
      - bearer_token: []
      description: 'Accepts a document binary as part of a multipart payload.

        Use this PUT endpoint after the POST endpoint for uploading the signed 21-22 PDF form.


        '
    get:
      summary: Check POA status by ID.
      tags:
      - Power of Attorney
      operationId: GET:/forms/2122/{id}
      security:
      - productionOauth:
        - claim.read
      - sandboxOauth:
        - claim.read
      - bearer_token: []
      description: Based on ID, returns a 21-22 submission and current status.
  /forms/2122/active:
    get:
      summary: Check active POA status.
      tags:
      - Power of Attorney
      operationId: GET:/forms/2122/active
      security:
      - productionOauth:
        - claim.read
      - sandboxOauth:
        - claim.read
      - bearer_token: []
      description: 'Returns the last active POA for a claimant.

        To check the status of new POA submissions, use the GET /forms/2122/{id} endpoint.


        '
  /forms/2122/validate:
    post:
      summary: 21-22 POA form submission test run.
      deprecated: true
      tags:
      - Power of Attorney
      operationId: POST:/forms/2122/validate
      security:
      - productionOauth:
        - claim.read
        - claim.write
      - sandboxOauth:
        - claim.read
        - claim.write
      - bearer_token: []
      description: 'Test to make sure the form submission works with your parameters.

        '
  /veterans/{veteranId}/power-of-attorney:
    get:
      summary: Retrieves current power of attorney
      tags:
      - Power of Attorney
      operationId: GET:/veterans/{veteranId}/power-of-attorney
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
      description: Retrieve a claimant’s currently appointed accredited representative with power of attorney (General POA) for the claimant. Returns empty data if no General POA is assigned.
  /veterans/{veteranId}/power-of-attorney-request:
    post:
      summary: Creates power of attorney request for an accredited representative
      description: Request the appointment of an accredited representative, on behalf of a claimant.
      tags:
      - Power of Attorney
      operationId: POST:/veterans/{veteranId}/power-of-attorney-request
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
  /veterans/power-of-attorney-requests:
    post:
      summary: Retrieves power of attorney requests for accredited representatives
      tags:
      - Power of Attorney
      operationId: POST:/veterans/power-of-attorney-requests
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
      description: Search for power of attorney requests by specified POA codes. Optional filters include searching by status, city, state, and country.
  /veterans/power-of-attorney-requests/{id}:
    get:
      summary: Retrieves a power of attorney request
      tags:
      - Power of Attorney
      operationId: GET:/veterans/power-of-attorney-requests/{id}
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
      description: Retrieve a power of attorney request by id.
  /veterans/power-of-attorney-requests/{id}/decide:
    post:
      summary: Submits representative decision for a power of attorney request
      tags:
      - Power of Attorney
      operationId: POST:/veterans/power-of-attorney-requests/{id}/decide
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
      description: Approve or decline a power of attorney request. If approved, the power of attorney request will be submitted to VA. The claimant will be notified of the decision by email.
  /veterans/{veteranId}/2122/validate:
    post:
      summary: Validates request to establish an organization as a claimant’s accredited representative
      tags:
      - Power of Attorney
      operationId: POST:/veterans/{veteranId}/2122/validate
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
      description: 'Validate a request to establish an organization with power of attorney (VA Form 21-22). Use POST

        /veterans/{veteranId}/2122 to automatically establish submit VA Form 21-22.

        '
  /veterans/{veteranId}/2122:
    post:
      summary: Automatically establishes an organization as a claimant’s accredited representative (VA Form 21-22)
      description: 'Submit VA Form 21-22 to automatically establish a VA accredited organization with power of attorney

        (General POA).

        '
      tags:
      - Power of Attorney
      operationId: POST:/veterans/{veteranId}/2122
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
  /veterans/{veteranId}/2122a/validate:
    post:
      summary: Validates request to establish an individual as a claimant’s accredited representative (VA Form 21-22a)
      tags:
      - Power of Attorney
      operationId: POST:/veterans/{veteranId}/2122a/validate
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
      description: 'Validate a request to establish an individual with power of attorney (VA Form 21-22a). Use POST

        /veterans/{veteranId}/2122a to automatically establish submit VA Form 21-22a.

        '
  /veterans/{veteranId}/2122a:
    post:
      summary: Automatically establishes an individual as a claimant’s accredited representative (VA Form 21-22a)
      tags:
      - Power of Attorney
      operationId: POST:/veterans/{veteranId}/2122a
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
      description: 'Submit VA Form 21-22 to automatically establish a VA accredited individual with power of attorney (General POA).

        '
  /veterans/{veteranId}/power-of-attorney/{id}:
    get:
      summary: Checks status of power of attorney submission (VA Forms 21-22 or 21-22a)
      description: Check the submissions status of a request to appoint power of attorney (VA Forms 21-22 or 21-22a).
      tags:
      - Power of Attorney
      operationId: GET:/veterans/{veteranId}/power-of-attorney/{id}
      security:
      - productionOauth:
        - system/claim.read
        - system/claim.write
      - sandboxOauth:
        - system/claim.read
        - system/claim.write
      - bearer_token: []
components:
  securitySchemes:
    apikey:
      type: apiKey
      name: apikey
      in: header
